version: '3.9'

services:
  # backend:
  #   container_name: express-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3005:3005"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB_PASSWORD=example
  #     - DB_NAME=job_board

  db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: job_board
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
